services:
  backapp:
    image: backapp-image
    container_name: backapp
  frontapp:    
    image: frontapp-image
    container_name: frontapp
    environment:
      - BACK_URL=http://backapp:8080
    ports:
      - "8080:8080" 